cacheFolder: ./.yarn/cache

checksumBehavior: throw

defaultLanguageName: node

defaultProtocol: "npm:"

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableStrictSsl: true

enableTelemetry: false

httpRetry: 3

httpTimeout: 60000

networkConcurrency: 8

nmHoistingLimits: none

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.2.cjs
